### ISSUE TITLE
Hangs indefinitely

### ISSUE THREAD

**Issue by MadcapJake** [MadcapJake/gx-perl6#1]
I get this `bt` after sigint in `perl6-gdb-m`:

```
#0  0x00007ffff78f6d13 in MVM_gc_root_add_frame_registers_to_worklist ()
   from /home/jrusso/.rakudobrew/moar-nom/install/lib/libmoar.so
#1  0x00007ffff78f71be in MVM_gc_root_add_frame_roots_to_worklist ()
   from /home/jrusso/.rakudobrew/moar-nom/install/lib/libmoar.so
#2  0x00007ffff78f56b6 in MVM_gc_worklist_mark_frame_roots ()
   from /home/jrusso/.rakudobrew/moar-nom/install/lib/libmoar.so
#3  0x00007ffff78f7bfc in process_worklist ()
   from /home/jrusso/.rakudobrew/moar-nom/install/lib/libmoar.so
#4  0x00007ffff78f824f in MVM_gc_collect ()
   from /home/jrusso/.rakudobrew/moar-nom/install/lib/libmoar.so
#5  0x00007ffff78f461e in run_gc ()
   from /home/jrusso/.rakudobrew/moar-nom/install/lib/libmoar.so
#6  0x00007ffff78f5067 in MVM_gc_enter_from_allocator ()
   from /home/jrusso/.rakudobrew/moar-nom/install/lib/libmoar.so
#7  0x00007ffff78f5198 in MVM_gc_allocate_nursery ()
   from /home/jrusso/.rakudobrew/moar-nom/install/lib/libmoar.so
#8  0x00007ffff78f53da in MVM_gc_allocate_object ()
   from /home/jrusso/.rakudobrew/moar-nom/install/lib/libmoar.so
#9  0x00007ffff78bf27b in MVM_args_slurpy_named ()
   from /home/jrusso/.rakudobrew/moar-nom/install/lib/libmoar.so
#10 0x00007ffff78c57b1 in MVM_interp_run ()
   from /home/jrusso/.rakudobrew/moar-nom/install/lib/libmoar.so
#11 0x00007ffff798b161 in MVM_vm_run_file ()
   from /home/jrusso/.rakudobrew/moar-nom/install/lib/libmoar.so
#12 0x00000000004010bb in main ()
```

**Comment by MadcapJake** [comment]
Solved! Was infinitely looping the linked list repo-chain.
